### ISSUE TITLE
How to test model on our testing images

### ISSUE THREAD

**Issue by ghost** [HanzhouLiu/DeblurDiNAT#1]
I am using the pretrained weights DeblurDiNATL.pth to test my own testing images. I have placed the pretrained model in the folder i.e. /results/DeblurDiNATL/models/DeblurDiNATL.pth. I have kept my testing images in the folder i.e. /DeblurDiNAT/input_images. I am ruuning script through: python predict_GoPro_test_results.py --job_name DeblurDiNATL --weight_name DeblurDiNATL.pth --blur_path /DeblurDiNAT/input_images. But I am encountering an error. 
The error is: Traceback (most recent call last):
  File "predict_GoPro_test_results.py", line 49, in <module>
    for img_name in os.listdir(blur_path + '/' + file):
NotADirectoryError: [Errno 20] Not a directory: '/home/hypersoft-gpu/Mahrukh_Ali_Khan/test/DeblurDiNAT/input_images/test6.jpg' 
Although the image having name test6.jpg is present in the respective folder

**Comment by HanzhouLiu** [comment]
Thanks for your attention to our work. I believe that error arises because   '/home/hypersoft-gpu/Mahrukh_Ali_Khan/test/DeblurDiNAT/input_images/test6.jpg' is a file name instead of a directory. Our GoPro test structure looks like: Folder/SubFolder/Img.png. You can just change the for loop starting from line 49. Or you can move your test images into a sub directory so that the GoPro test codes work.

We will updated the other test codes, training codes, test results in future. Please stay tuned.
